model = "gpt-5.5"
model_reasoning_effort = "medium"
personality = "pragmatic"

[projects."/Users/channing/dev/ds"]
trust_level = "trusted"

[projects."/Users/channing/dev"]
trust_level = "trusted"

[projects."/Users/channing/dev/patchwork"]
trust_level = "trusted"

[projects."/Users/channing/dev/patchwork/repos/PatchworkOnRails"]
trust_level = "trusted"

[projects."/Users/channing/dotfiles"]
trust_level = "trusted"

[projects."/Users/channing/dev/fabric/fabric-space"]
trust_level = "trusted"

[projects."/Users/channing/dev/fabric/fabric-lite"]
trust_level = "trusted"

[projects."/Users/channing/dev/patchwork/repos"]
trust_level = "trusted"

[projects."/Users/channing/dev/patchwork/repos/kmono"]
trust_level = "trusted"

[projects."/Users/channing/dev/fabric/fabric-skill"]
trust_level = "trusted"

[projects."/Users/channing/dev/chatter-example"]
trust_level = "trusted"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[plugins."github@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."notion@openai-curated"]
enabled = true

[plugins."atlassian-rovo@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING = "1"
CLAUDE_CODE_DISABLE_AUTO_MEMORY = "0"
ENABLE_LSP_TOOL = "1"

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-04-25T13:50:40Z"
source_type = "local"
source = "/Users/channing/dotfiles/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-04-24T19:13:35Z"
source_type = "local"
source = "/Users/channing/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.datadog]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp"
