ghe.siriusxm.com:
    git_protocol: https
    users:
        cwalton:
    user: cwalton
github.com:
    git_protocol: https
    users:
        channingwalton:
        channing-txodds:
    user: channing-txodds
