ConfigFile = '/Users/channing/.config/lazysql/config.toml'
LocalConfigFile = ''

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100
TreeWidth = 30
JSONViewerWordWrap = false
EnterOpensJSONViewer = false

