theme = "tokyonight"

[editor]
true-color = true
color-modes = true
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "workspace-diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

# Stop Document popup automatically display when entering insert mode
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":w"
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight", ":redraw"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space]
x = ":buffer-close"
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.space]
d = ":lsp-workspace-command doctor-run"
c = ":lsp-workspace-command compile-clean"

[keys.insert]
C-space = "completion"
C-s = ":w"
