[[language]]
name = "scala"
auto-format = false

[language-server.metals.config]
isHttpEnabled = true
icons = "unicode"

[language-server.metals.config.metals]
autoImportBuild = "all"
showImplicitArguments = true
showImplicitConversionsAndClasses = true
showInferredType = true
superMethodLensesEnabled = true

[language-server.metals.config.metals.inlayHints]
inferredTypes.enable = true
typeParameters.enable = false
hintsInPatternMatch.enable = true
implicitArguments.enable = false
implicitConversions.enable = false

[[language]]
name = "unison"
language-servers = [ "ucm" ]
