[[language]]
name = "scala"
auto-format = false

[language-server.metals.config]
isHttpEnabled = true
icons = "unicode"

[language-server.metals.config.metals]
autoImportBuild = "all"
defaultBspToBuildTool = true
mcpClient = true
showImplicitArguments = true
showImplicitConversionsAndClasses = true
showInferredType = true
startMcpServer = true
superMethodLensesEnabled = true
useGlobalExecutable = true

[language-server.metals.config.metals.inlayHints]
byNameParameters.enable = true
hintsInPatternMatch.enable = true
hintsXRayMode.enble=true
implicitArguments.enable = false
implicitConversions.enable = false
inferredTypes.enable = true
typeParameters.enable = false

[language-server.ucm]
command = "nc"               # brew install netcat
args = ["localhost", "5757"]

[[language]]
name = "unison"
language-servers = ["ucm"]
