[[language]]
name = "scala"
auto-format = false

[language-server.metals.config]
isHttpEnabled = true
icons = "unicode"

[language-server.metals.config.metals]
autoImportBuild = "all"
showImplicitArguments = true
showImplicitConversionsAndClasses = true
showInferredType = true
superMethodLensesEnabled = true
defaultBspToBuildTool = true

[language-server.metals.config.metals.inlayHints]
inferredTypes.enable = true
typeParameters.enable = false
hintsInPatternMatch.enable = true
implicitArguments.enable = false
implicitConversions.enable = false

[language-server.ucm]
command = "nc"               # brew install netcat
args = ["localhost", "5757"]

[[language]]
name = "unison"
language-servers = ["ucm"]
