[tools]
node   = "26.9.0"
ruby   = "4.0.7"
java   = "zulu-25"
python = "3.14"
rust = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
pnpm = "latest"
maven = "latest"
gradle = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby", "python"]
disable_tools = ["bundler"]
